### ISSUE TITLE
Indexes only being listed from Search Heads

### ISSUE THREAD

**Issue by ryanwoconnor** [HurricaneLabs/flunk#1]
I've uncovered an issue where indexes are being listed from the Search Head, but if different indexes reside solely on an Indexer, those are not being displayed. Feel free to reach out to me for a specific example.

**Comment by mcm** [comment]
Unfortunately that's by design. All flunk does is return data from the REST endpoints, and as far as I'm aware there isn't one that exposes the remote indexes.
